### ISSUE TITLE
Input board, pull up I2C communication resistors 

### ISSUE THREAD

**Issue by kretowicz14** [boneIO-eu/boneIO#109]
From input board v0.6 we need to change resistors near PCA9515 from 10k ohm to 3,3k ohm.
Before change signals from SCL & SDA are to low and make problems with communication, after change signals are more stronger and super stable even with 3m cable.
More details on discord topic: **help-forum -> Analiza I2C i problemów z expanderami**

**Comment by kamil2466** [comment]
Changes will be introduced in the next version of the board
