### ISSUE TITLE
12 or 24 V output on MOSFETs

### ISSUE THREAD

**Issue by zibijw23** [boneIO-eu/boneIO#111]
Is there a plan to produce a board version with a 12 or 24 V output to control a bistable relay mounted in a control cabinet on a DIN rail?

**Comment by ensimek** [comment]
> Is there a plan to produce a board version with a 12 or 24 V output to control a bistable relay mounted in a control cabinet on a DIN rail?

There's a MOSFET you can buy. I have it already in my cabinet. It controls my external 12V Relpol Relays
