### ISSUE TITLE
Input Board ESP32 v0.1

### ISSUE THREAD

**Issue by kamil2466** [boneIO-eu/boneIO#72]
Witam, stworzyłem schemat płytki dla ESP32 chciałem aby osoby które maja doświadczenie pomogły trochę tworzeniu projektu, może macie jakieś sugestie lub chcecie zmian albo gdzieś jest błąd to proszę o komentowanie.
[input board ESP32.pdf](https://github.com/maciejkrasuski/boneIO/files/7662007/input.board.ESP32.pdf)
![image](https://user-images.githubusercontent.com/37997460/144881371-8b5c30a5-cf59-4d6f-a9d6-cf42d7252c44.png)

**Comment by pepsonEL** [comment]
Kurczę nie za bardzo jeszcze ogarniam takie schematy bo tak bym pomógł.....

**Comment by th0m4sek** [comment]
jaki pin odpowiada za sterowanie multiplexerem i czy rezygnacja z interuptow dla MCP nie bedzie problemem przy tylu wejsciach ?

**Comment by kamil2466** [comment]
Sterowanie jest zworka. Zworka założona to możliwość programowania zdjęta to wyjście na złączkę. Odnoście MCP to nie powinno być problemu, będziemy testować i zobaczymy

**Comment by th0m4sek** [comment]
A może wykrywać by 5v z portu USB który podłączony będzie tylko jeśli chcemy go uzywac

**Comment by th0m4sek** [comment]
A i czy gpio 39 jest do czegoś użyte?

**Comment by kamil2466** [comment]
Możemy zrobić tak że jak podepnie się wtyczkę pod USB to 5v z USB przestawi na multiplexer na programowanie, a odnośnie gpio39 jest wolne bo to input a już nie mamy wolnej złączki

**Comment by th0m4sek** [comment]
To podpinać 39 pod interrupts nawet jak się nie użyje to nie zaszkodzi a już 8 będzie obsługiwało przerwania ;) i będzie można potraktować ;)

**Comment by kamil2466** [comment]
Ok. Jakiś pullup lub pulldown się robi ? Najlepiej przedstaw swoją propozycję na schemacie

**Comment by th0m4sek** [comment]
https://arduino.stackexchange.com/questions/26898/using-interrupts-for-two-mcp23017
Tu piszą że wystarczy pullup i że nawet więcej ekspanderów można do jednego pinu spiąć.

**Comment by kamil2466** [comment]
@th0m4sek napisz do mnie na PW FB lub discord

**Comment by th0m4sek** [comment]
Już albo napisałem do kogoś innego na FB jak coś to na FB jestem jako Tomasz Dziliński

**Comment by JakubIgnacyGorski** [comment]
Witam, zacząłem robić swoje zanim tu spojrzałem więc może podzielę się moim pomysłem na boneIO sterowane za pomocą ESP32. Liczę na poprawki mądrzejszych ode mnie gdyż jestem początkującym elektronikiem :)
[input_board_ESP32_v0.1.pdf](https://github.com/boneIO-eu/boneIO/files/7959159/input_board_ESP32_v0.1.pdf)
 
 Przy okazji chciałem się spytać tylko jak wygląda postęp Pana (@kamil2466) projektu?

**Comment by kamil2466** [comment]
@JakubIgnacyGorski  nie panujemy sobie :)
Ten schemat nie aktualny, zrobony jest nowy schemat i płytka zamówiona. Powinna być na dniach u mnie. Co do twojego schematu to wszystko podobnie i tak na marginesie CP2021 ciezkie do lutowania i dlatego CH340G ja stosowałem a automat zmiany zasilania nie działa. :)

**Comment by JakubIgnacyGorski** [comment]
@kamil2466 o dobrze że mówisz wywalę ten automat. I tak na razie poczekam z projektem PCB bo zaraz się okaże że niepotrzebnie to robię i twój projekt spełni moje oczekiwania ;)

**Comment by maciejkrasuski** [comment]
Czy coś tu jeszcze się dzieje, czy można zamykać ten issue?

**Comment by kamil2466** [comment]
tak do zamknięcia schemat nie aktualny
