### ISSUE TITLE
Wyświetlacz - dodanie do dokumentacji info o kolejności pinów

### ISSUE THREAD

**Issue by Bolo92** [boneIO-eu/boneIO#87]
Ten model wyświetlacza posiada różną kolejność PINów. BoneIO jest przystosowane do VDD, GND, SCK, SDA, natomiast niektóre mają GND, VCC, SCL, SDA.
Do dodania w dokumentacji I/lub w google sheet w arkuszu o BOM/THT.
Na discordzie było już parę pytań czemu wyświetlacz nie działa właśnie z tego powodu.

**Comment by maciejkrasuski** [comment]
Done https://docs.boneio.eu/en/stable/boards/input_board.html#assembling-components
